on: ["push", "pull_request"]

name: Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Ganache
        run: |
          pushd vyper
          npm install
          popd

      - name: Install vyper and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vyper==0.2.11
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install eth-brownie
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test vyper
        run: |
          pushd vyper
          brownie test
          popd

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn
        run: yarn

      - name: coverage
        run: yarn coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
